---
settings:
  name: E-Series
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de E-Series
    url: "/index.html"
  - title: Notas de la versión
    url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Descubra sus sistemas E-Series
      url: "/task-discover-e-series.html"
  - title: Gestione clústeres E-Series
    entries:
    - title: Vea sus sistemas E-Series
      url: "/task-view-e-series.html"
    - title: Elimine E-Series
      url: "/task-remove-e-series.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Descubra sus sistemas E-Series
      url: "/task-discover-e-series.html"
  - title: Gestione los sistemas E-Series
    links:
    - title: Vea sus sistemas E-Series
      url: "/task-view-e-series.html"
    - title: Elimine E-Series
      url: "/task-remove-e-series.html"
  - title: Enlaces relacionados
    links:
    - title: Documentación de E-Series para gestión fuera de BlueXP
      url: https://docs.netapp.com/us-en/e-series-family/
  - title: Blogs y comunidad
    links:
    - title: Comunidad de NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog de BlueXP
      url: https://cloud.netapp.com/blog
    - title: Seminarios web sobre el cloud
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: Toda la documentación de BlueXP
